spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing_db
    username: postgres
    password: Sigma2002@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}